name: Metrics
on:
  push:
    branches:
      - v4-dev
  #pull_request:
  #  branches:
  #    - v4-dev
  #  paths-ignore:
  #    - "**/*.md"
jobs:
  # Lint, format, build and test
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - ci:check
          - ci:test
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno task btr ${{ matrix.task }}

  # GitHub CodeQL analysis
  analyze:
    runs-on: ubuntu-latest
    needs:
      - testing
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - typescript
    steps:
    - uses: actions/checkout@v4
    - uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config: |
          queries:
            - uses: security-and-quality
          paths-ignore:
            - source/run/server/imports.ts
    - uses: github/codeql-action/analyze@v2

  # Build and push Docker image
  docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/v4-dev'
    runs-on: ubuntu-latest
    needs:
      - analyze
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5
        with:
          tags: v4
          file: ./Dockerfile
          push: true