name: Metrics
on:
  push:
    branches:
      - v4-dev
  pull_request:
    branches:
      - v4-dev
    paths-ignore:
      - "**/*.md"
jobs:
  # Lint, format, build and test
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - ci:check
          - ci:test
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: deno task btr ${{ matrix.task }}

  # GitHub CodeQL analysis
  analyze:
    name:
    runs-on: ubuntu-latest
    needs:
      - testing
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - typescript
    steps:
    - uses: actions/checkout@v3
    - uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config: |
          queries:
            - uses: security-and-quality
          paths-ignore:
            - source/run/server/imports.ts
    - uses: github/codeql-action/analyze@v2
